import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ControlClient } from '../services/controlClient.js';
import { PlatformClient, type AuditLog, type Lease, type PlatformUser, type TrackPoint, type Vehicle } from '../services/platformClient.js';
import { TrackMap } from '../components/TrackMap.js';

type Page = 'dashboard' | 'vehicles' | 'map' | 'users' | 'audit';
interface ActiveControl { vehicle: Vehicle; lease: Lease; }
const client = new PlatformClient();

function Login({ onLogin, onClassic }: { onLogin: (user: PlatformUser) => void; onClassic: () => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { setError(''); onLogin((await client.login(username, password)).user); } catch (reason) { setError(reason instanceof Error ? reason.message : '登录失败'); } };
  return <main className="login-page"><section className="panel login-panel"><p className="eyebrow">OH AI CAR PLATFORM</p><h1>车辆管理平台</h1><p>使用管理员创建的账号登录，管理车辆、轨迹和本机控制租约。</p><form onSubmit={submit}><label>用户名<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" /></label><label>密码<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" /></label>{error && <p className="error">{error}</p>}<button type="submit">登录平台</button></form><button className="secondary" onClick={onClassic}>使用原本机控制台</button></section></main>;
}

export function PlatformConsole({ onClassic }: { onClassic: () => void }) {
  const gateway = useMemo(() => new ControlClient(), []); const [user, setUser] = useState<PlatformUser | null>(null); const [page, setPage] = useState<Page>('dashboard'); const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [selected, setSelected] = useState<Vehicle | null>(null); const [track, setTrack] = useState<TrackPoint[]>([]); const [audit, setAudit] = useState<AuditLog[]>([]); const [users, setUsers] = useState<PlatformUser[]>([]); const [active, setActive] = useState<ActiveControl | null>(null); const [status, setStatus] = useState(''); const [playing, setPlaying] = useState(false); const [playbackIndex, setPlaybackIndex] = useState<number | null>(null); const activeRef = useRef<ActiveControl | null>(null);
  const refreshVehicles = useCallback(async () => { const next = (await client.vehicles()).vehicles; setVehicles(next); setSelected((current) => current ? next.find((vehicle) => vehicle.id === current.id) ?? null : next[0] ?? null); }, []);
  const refreshTrack = useCallback(async (vehicle: Vehicle | null) => { if (!vehicle) return setTrack([]); setTrack((await client.track(vehicle.id)).points); }, []);
  useEffect(() => { void client.me().then(({ user: next }) => { setUser(next); return refreshVehicles(); }).catch(() => setUser(null)); }, [refreshVehicles]);
  useEffect(() => { void refreshTrack(selected); }, [selected, refreshTrack]);
  useEffect(() => { setPlaying(false); setPlaybackIndex(null); }, [selected]);
  useEffect(() => {
    if (!selected || !user) return;
    const endpoint = new URL(client.baseUrl); endpoint.protocol = endpoint.protocol === 'https:' ? 'wss:' : 'ws:'; endpoint.pathname = '/ws';
    const socket = new WebSocket(endpoint); socket.addEventListener('open', () => socket.send(JSON.stringify({ type: 'subscribe', vehicleId: selected.id })));
    socket.addEventListener('message', (event) => { const message = JSON.parse(String(event.data)) as { type?: string; vehicleId?: string; payload?: TrackPoint }; if (message.type === 'vehicle.position' && message.vehicleId === selected.id && message.payload) setTrack((current) => current.some((point) => point.occurredAt === message.payload?.occurredAt) ? current : [...current, message.payload!]); });
    return () => socket.close();
  }, [selected, user]);
  useEffect(() => { if (!playing || playbackIndex === null || playbackIndex >= track.length - 1) return; const timer = window.setTimeout(() => setPlaybackIndex((current) => current === null ? null : Math.min(current + 1, track.length - 1)), 700); return () => window.clearTimeout(timer); }, [playing, playbackIndex, track.length]);
  useEffect(() => { activeRef.current = active; }, [active]);
  useEffect(() => () => gateway.close(), [gateway]);
  useEffect(() => { if (!active) return; const timer = window.setInterval(() => { void client.renewLease(active.lease.leaseId).then((renewed) => { const next = { ...active, lease: { ...renewed, leaseId: active.lease.leaseId } }; setActive(next); return gateway.send('leaseRefresh', { host: next.vehicle.host, tcpPort: next.vehicle.tcpPort, videoPort: next.vehicle.videoPort, vehicleId: next.vehicle.id, leaseToken: next.lease.gatewayToken }); }).catch(async () => { setStatus('控制租约续期失败，正在安全断开。'); try { await gateway.send('disconnect', {}); } catch { /* gateway may already be closed */ } setActive(null); }); }, 20_000); return () => window.clearInterval(timer); }, [active, gateway]);
  const connect = async (vehicle: Vehicle) => { try { setStatus('正在申请控制租约…'); const lease = await client.acquireLease(vehicle.id); await gateway.open(); await gateway.send('connect', { host: vehicle.host, tcpPort: vehicle.tcpPort, videoPort: vehicle.videoPort, vehicleId: vehicle.id, leaseToken: lease.gatewayToken }); setActive({ vehicle, lease }); setStatus(`已通过本机网关连接 ${vehicle.name}`); } catch (reason) { setStatus(reason instanceof Error ? reason.message : '连接失败'); } };
  const disconnect = async () => { const current = activeRef.current; try { await gateway.send('disconnect', {}); } catch { /* safety close is best effort */ } if (current) await client.releaseLease(current.lease.leaseId).catch(() => undefined); setActive(null); setStatus('已安全断开本机控制。'); };
  const loadAdmin = async (next: Page) => { setPage(next); if (next === 'users') setUsers((await client.users()).users); if (next === 'audit') setAudit((await client.audit()).logs); };
  const logout = async () => { await disconnect(); await client.logout().catch(() => undefined); setUser(null); };
  if (!user) return <Login onLogin={(next) => { setUser(next); void refreshVehicles(); }} onClassic={onClassic} />;
  const nav = (id: Page, label: string) => <button className={page === id ? 'nav-active' : 'secondary'} onClick={() => void loadAdmin(id)}>{label}</button>;
  const lastPoint = track.at(-1);
  const visibleTrack = playbackIndex === null ? track : track.slice(0, playbackIndex + 1);
  return <main className="platform-shell"><header><div><p className="eyebrow">OH AI CAR PLATFORM</p><h1>车辆管理平台</h1></div><div className="account-row"><span>{user.displayName}（{user.role === 'admin' ? '管理员' : '操作员'}）</span><button className="secondary" onClick={onClassic}>本机控制台</button><button className="secondary" onClick={() => void logout()}>退出</button></div></header><nav className="platform-nav">{nav('dashboard', '仪表盘')}{nav('vehicles', '车辆')}{nav('map', '轨迹地图')}{user.role === 'admin' && nav('users', '用户')}{user.role === 'admin' && nav('audit', '审计')}</nav>{status && <p className="notice">{status}</p>}
    {page === 'dashboard' && <section className="metric-grid"><article className="panel"><h2>已授权车辆</h2><strong>{vehicles.length}</strong></article><article className="panel"><h2>当前控制</h2><strong>{active ? active.vehicle.name : '未连接'}</strong></article><article className="panel"><h2>最新轨迹</h2><strong>{lastPoint ? new Date(lastPoint.occurredAt).toLocaleString() : '暂无数据'}</strong></article></section>}
    {page === 'vehicles' && <section className="two-column"><section className="panel"><h2>已保存车辆</h2><div className="vehicle-list">{vehicles.map((vehicle) => <button key={vehicle.id} className={selected?.id === vehicle.id ? 'nav-active' : 'secondary'} onClick={() => setSelected(vehicle)}>{vehicle.name}<small>{vehicle.code}</small></button>)}</div></section><section className="panel"><h2>{selected?.name ?? '选择一辆车'}</h2>{selected && <><p>{selected.description || '暂无描述'}</p><dl><dt>TCP</dt><dd>{selected.host}:{selected.tcpPort}</dd><dt>视频</dt><dd>{selected.videoPort}</dd></dl>{active?.vehicle.id === selected.id ? <button className="danger" onClick={() => void disconnect()}>安全断开</button> : <button onClick={() => void connect(selected)}>申请租约并本机连接</button>}<div className="control-shortcuts"><button disabled={!active || active.vehicle.id !== selected.id} onClick={() => void gateway.send('button', { direction: 'Front' })}>前进</button><button disabled={!active || active.vehicle.id !== selected.id} onClick={() => void gateway.send('button', { direction: 'Stop' })}>停止</button><button disabled={!active || active.vehicle.id !== selected.id} onClick={() => void gateway.send('button', { direction: 'Brake' })}>刹车</button></div></>}</section></section>}
    {page === 'map' && <><section className="panel filter-row"><label>车辆<select value={selected?.id ?? ''} onChange={(event) => setSelected(vehicles.find((vehicle) => vehicle.id === event.target.value) ?? null)}>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.name}</option>)}</select></label><button onClick={() => void refreshTrack(selected)}>刷新最近 24 小时</button><button disabled={!track.length} onClick={() => { setPlaybackIndex((current) => current ?? 0); setPlaying((current) => !current); }}>{playing ? '暂停回放' : '播放回放'}</button><button className="secondary" disabled={!track.length} onClick={() => { setPlaying(false); setPlaybackIndex(null); }}>显示完整轨迹</button><span>{track.length} 个点，最近点 {lastPoint ? new Date(lastPoint.occurredAt).toLocaleString() : '无'}</span></section><TrackMap points={visibleTrack} /></>}
    {page === 'users' && <section className="panel"><h2>用户</h2><table><thead><tr><th>用户名</th><th>显示名</th><th>角色</th><th>状态</th></tr></thead><tbody>{users.map((entry) => <tr key={entry.id}><td>{entry.username}</td><td>{entry.displayName}</td><td>{entry.role}</td><td>{entry.active ? '启用' : '停用'}</td></tr>)}</tbody></table></section>}
    {page === 'audit' && <section className="panel"><h2>审计日志</h2><table><thead><tr><th>时间</th><th>动作</th><th>结果</th><th>车辆</th></tr></thead><tbody>{audit.map((entry) => <tr key={entry.id}><td>{new Date(entry.createdAt).toLocaleString()}</td><td>{entry.action}</td><td>{entry.outcome}</td><td>{entry.vehicleId ?? '-'}</td></tr>)}</tbody></table></section>}
  </main>;
}
